Repository brave/muon, pull requests merged in 2018-04, with the labels that each got.

#557 Replace GURL for tor browser context
  brave/browser/BUILD.gn
  brave/browser/brave_browser_context.cc
  brave/browser/brave_browser_context.h
  brave/browser/net/proxy/proxy_config_service_tor.cc
  brave/browser/net/proxy/proxy_config_service_tor.h
  brave/utility/tor/tor_impl.cc
Labels: merged/WIP-branch

#570 Revert "Merge pull request #484 from brave/quarantine_downloads"
  app/mac/resources/app-Info.plist
  app/mac/resources/helper-Info.plist
Labels: branch-5.1.x

#575 Update external binaries to 1.3.0 for latest Squirrel.Mac
  script/update-external-binaries.py
Labels: branch-5.2.x, branch-6.0.x

#563 Fix undefined symbols of chromium_src/net on Windows
  chromium_src/BUILD.gn
  patches/master_patch.patch
Labels: feature/tor
