Repository brave/muon, pull requests merged in 2018-02, with the labels that each got.

#482 fix windows build error
  app/BUILD.gn
Labels: branch-4.8.x, branch-5.0.x

#493 ensure that `session-created` fires for the main browser context
  atom/browser/atom_browser_main_parts.cc
Labels: branch-4.8.x, branch-5.0.x

#497 Hide title bar bg on Mac for non-normal styles.
  atom/browser/native_window_mac.mm
Labels: branch-5.0.x

#484 Downloaded files on macOS should be quarantined by default
  app/mac/resources/app-Info.plist
  app/mac/resources/helper-Info.plist
Labels: branch-5.0.x, security

#495 Don't set ACTIVATABLE_NO when `show: false` on Linux
  atom/browser/native_window_views.cc
Labels: branch-5.0.x

#486 Update ad-block dependency to latest version
  DEPS
Labels: branch-4.8.x, branch-5.0.x

#503 Obtain extension from path when no mime type available
  atom/browser/atom_download_manager_delegate.cc
Labels: branch-5.0.x

#504 Fix/tabs discard dead tab
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/extensions/tab_helper.cc
  atom/common/api/resources/web_view_api_bindings.js
  brave/browser/guest_view/tab_view/tab_view_guest.cc
Labels: branch-5.0.x

#511 Fix empty devtool profile
  atom/browser/common_web_contents_delegate.cc
Labels: branch-5.0.x

#509 PR 503 followup
  atom/browser/atom_download_manager_delegate.cc
  atom/browser/atom_download_manager_delegate.h
  brave/browser/guest_view/tab_view/tab_view_guest.cc
Labels: branch-5.0.x
