Repository brave/muon, pull requests merged in 2018-03, with the labels that each got.

#508 Using `DIR_DEFAULT_DOWNLOADS_SAFE`
  atom/browser/api/atom_api_dialog.cc
Labels: branch-5.0.x

#522 Handle download from newly created tab
  atom/browser/atom_download_manager_delegate.cc
Labels: branch-4.9.x

#529 Fix https://github.com/brave/browser-laptop/issues/13365
  atom/browser/atom_download_manager_delegate.cc
Labels: branch-4.9.x

#532 Add Session API to clear HSTS entries
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_session.h
Labels: branch-5.1.x

#546 Fix printing service on Windows
  atom/utility/atom_content_utility_client.cc
  brave/browser/brave_content_browser_client.cc
Labels: branch-5.1.x

#545 Handle mouse up/down in async
  patches/master_patch.patch
Labels: branch-5.1.x

#542 Add filesystem `type` for dev tools
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/common_web_contents_delegate.cc
  atom/browser/common_web_contents_delegate.h
  vendor/brightray/browser/inspectable_web_contents_delegate.h
  vendor/brightray/browser/inspectable_web_contents_impl.cc
  vendor/brightray/browser/inspectable_web_contents_impl.h
Labels: branch-5.1.x

#540 Incorrect hosts were granted `OpenExternal` permissions
  atom/browser/atom_resource_dispatcher_host_delegate.cc
  atom/browser/web_contents_permission_helper.cc
  atom/browser/web_contents_permission_helper.h
  brave/browser/brave_permission_manager.cc
Labels: branch-5.1.x

#551 fix windows create_dist
  app/win/BUILD.gn
  tools/win/generate_breakpad_symbols.py
Labels: branch-5.1.x

#470 SOCKS5 authentication support
  chromium_src/BUILD.gn
  chromium_src/net/base/host_port_pair_auth.cc
  chromium_src/net/base/url_auth_util.cc
  chromium_src/net/base/url_auth_util.h
  chromium_src/net/socket/socks5_client_socket_auth.cc
  chromium_src/net/socket/socks5_client_socket_auth.h
  patches/master_patch.patch
Labels: branch-5.1.x, feature/tor
